object Compose {
    private const val composeVersion = "1.8.2"
    private const val viewModelComposeVersion = "2.5.1"
    private const val navigationVersion = "2.5.3"
    private const val lifeCycleVersion = "2.6.2"
    private const val hiltNavigationVersion = "1.1.0-alpha01"

    const val activityCompose = "androidx.activity:activity-compose:$composeVersion"
    const val composeBom = "androidx.compose:compose-bom:2023.08.00"
    const val composeUi = "androidx.compose.ui:ui"
    const val composeGraphics = "androidx.compose.ui:ui-graphics"
    const val composeToolingPreview = "androidx.compose.ui:ui-tooling-preview"
    const val composeMaterial3 = "androidx.compose.material3:material3"
    const val composeUiTooling = "androidx.compose.ui:ui-tooling"
    const val composeTestManifest = "androidx.compose.ui:ui-test-manifest"
    const val composeLifecycleViewModel = "androidx.lifecycle:lifecycle-viewmodel-compose:$viewModelComposeVersion"
    const val composeLifecycle = "androidx.lifecycle:lifecycle-runtime-compose:$lifeCycleVersion"
    const val composeHiltNavigation = "androidx.hilt:hilt-navigation-compose:$hiltNavigationVersion"
    const val composeNavigation = "androidx.navigation:navigation-compose:$navigationVersion"
}
